name: Backend
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    branches:
      - master

  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
    types:
      - opened
      - synchronize
      - reopened
  
jobs:
  sonarqube: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: backend
        # args: -Dproject.settings=packages/simple-react-app/sonar-scanner.properties
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_SECRET_2 }}
        SONAR_HOST_URL: https://gbqipwdfkw.a.pinggy.link
